-- MySQL Script generated by MySQL Workbench
-- Thu Jan 10 20:12:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_catalago
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_catalago
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_catalago` DEFAULT CHARACTER SET utf8 ;
USE `db_catalago` ;

-- -----------------------------------------------------
-- Table `db_catalago`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_catalago`.`empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `nome_emp` VARCHAR(100) NULL,
  `cnpj_cpf` VARCHAR(45) NULL,
  `razao_social` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `status_emp` VARCHAR(45) NULL,
  `data_cadastro_emp` TIMESTAMP NULL,
  PRIMARY KEY (`idempresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_catalago`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_catalago`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome_user` VARCHAR(45) NULL,
  `email_user` VARCHAR(45) NULL,
  `senha_user` VARCHAR(45) NULL,
  `nivel_user` VARCHAR(45) NULL,
  `status_user` VARCHAR(45) NULL,
  `data_cadastro_user` TIMESTAMP NULL,
  `empresa_idempresa` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_empresa_idx` (`empresa_idempresa` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_empresa`
    FOREIGN KEY (`empresa_idempresa`)
    REFERENCES `db_catalago`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_catalago`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_catalago`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome_prod` VARCHAR(45) NULL,
  `quatidade_prod` INT NULL,
  `foto_prod` VARCHAR(45) NULL,
  `valor_prod` FLOAT NULL,
  `status_prod` VARCHAR(45) NULL,
  `data_cadastro_prod` TIMESTAMP NULL,
  `empresa_idempresa` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idproduto`),
  INDEX `fk_produto_empresa1_idx` (`empresa_idempresa` ASC) VISIBLE,
  INDEX `fk_produto_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_produto_empresa1`
    FOREIGN KEY (`empresa_idempresa`)
    REFERENCES `db_catalago`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `db_catalago`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
